language: java
jdk:
  - oraclejdk8
addons:
  - postgresql: "9.4"
before_install:
  psql -c 'create database sc68_test;' -U postgres

env:
  - URL=jdbc:postgresql://localhost:5433/sc68_test USER=postgres

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

