language: java
jdk: oraclejdk8
services:
- postgresql
addons:
  postgresql: '9.4'
before_install:
- psql -c 'create database sc68_test;' -U postgres
- psql -c "alter user postgres password 'test';"
env: URL=jdbc:postgresql://localhost:5432/sc68_test USER=postgres PASSWORD=test TEST_URL=jdbc:postgresql://localhost:5432/sc68_test
  TEST_USER=postgres TEST_PASSWORD=test
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test
deploy:
  provider: heroku
  app: sc68backend
  on:
    repo: p-engelkes/sc68_backend
    branch: travis-ci
  api_key: 2e82ac0c-5af0-41d6-baa7-dcd16e298fea

