language: java
jdk:
  oraclejdk8

services:
  postgresql

before_install:
  - psql -c "alter user postgres password 'test';"

env:
  URL=jdbc:postgresql://localhost:5433/sc68_test USER=postgres PASSWORD=test

install:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test

