language: java
jdk: oraclejdk8
services:
- postgresql
addons:
  postgresql: '9.4'
before_install:
- psql -c 'create database sc68_test;' -U postgres
- psql -c "alter user postgres password 'test';"
env: URL=jdbc:postgresql://localhost:5432/sc68_test USER=postgres PASSWORD=test TEST_URL=jdbc:postgresql://localhost:5432/sc68_test
  TEST_USER=postgres TEST_PASSWORD=test
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test
deploy:
  provider: heroku
  app: murmuring-sierra-50342
  on:
    repo: p-engelkes/sc68_backend
    branch: travis-ci
  api_key:
    secure: K5fWfmfJjsMvtOJ1Ycc3CdWn9m0pRxYXM23zNAX6h1PEPwTSn3LRm3CBHlixZHF1OJ2cn5eqwrJLKgTVeeJqByzPh28FQAV6TpP+iNpogzGmfyBaMyUMgz+LgG6S4jKPMQl5vW6g2KmVSRFdZBxNGYZtmPqM7mu4KSSaTm5QfxLG1RZ1wZ3yswF6e4zl0AdKEtGDUruR+ztnDxAOM86fEsxc03NjDNPakA2OEscitTghXYzJxk1QkOIA/v1qOgVxvkbYYyugqoR3T2G+YquVwZXQ367XlC7MDUR2GxhsQS5h++pUVMuiVmpnMRhRd5By+ahdtaPS5uEGq6y3nuiHnrDMrJVXL/0LlD8dZUjEn7CIV1bLLA22KGROibxkdMjvckMGmvJhKpGtbrOX3bsctoJkiTtS7VrxMo5eRCGAnZ74uJt+fKm/v39KmN0f5wJuuDQvIJ9hhOfAomb03b2IBOVhsnQ5WdPAODW00Ri5LskLbOuPj7OPOKRp7PMK2yVkoefnMq/QFKOSsjBiK1Zfjuk4eeIXe6bUUSudCvMdf6a/s2JgMPvzneRZ8NJHK4PTkgK0UuWJ3Fon4XSqX3nOpgghOy6JOwbnLzzTrzy9A3R2ivUgv9I4N77p74ZlotcsvVnkfdsdFSsDclhy8VqkGHxeNFp/TfN5qCGFKXIdUQs=
